[project]
name = "stackodds"
description = "Prototype LMSR-style prediction market on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.token]
path = "contracts/token.clar"
epoch = 2.05

[contracts.market]
path = "contracts/market.clar"
epoch = 2.05

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
